import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import AuthProvider from './api/auth/provider'
const montserrat = Montserrat({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
})
import Header from '@/components/Common/Header'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={montserrat.className} suppressHydrationWarning={true}>
        <Header />
        <AuthProvider>
          <main className="h-screen">{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
