import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import AuthProvider from './api/auth/provider'
import SignInInput from '@/components/SignIn/SignInInput'
const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <AuthProvider>
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
